language: go

go:
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

env:
  - CC=arm-linux-gnueabihf-gcc
  - CXX=arm-linux-gnueabihf-g++
  - LD=arm-linux-gnueabihf-g++
  - AR=arm-linux-gnueabihf-ar
  - STRIP=arm-linux-gnueabihf-strip
  - CGO_ENABLED=1
  - GOOS=linux
  - GOARCH=arm
  - CC_FOR_TARGET=arm-linux-gnueabihf-gcc
  - CXX_FOR_TARGET=arm-linux-gnueabihf-g++
  - CPATH=${GOPATH}/src/github.com/supcik-go/ws2811/rpi_ws281x
  - LIBRARY_PATH=${GOPATH}/src/github.com/supcik-go/ws2811/rpi_ws281x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf
  - go get -d github.com/supcik-go/ws2811
  - cd ${GOPATH}/src/github.com/supcik-go/ws2811
  - git clone https://github.com/jgarff/rpi_ws281x.git
  - cd rpi_ws281x
  - patch -i ${TRAVIS_BUILD_DIR}/01_cross.patch
  - scons
  - sudo -E go install std

install:
  - patch -i ${TRAVIS_BUILD_DIR}/02_go.patch